### ISSUE TITLE
Panic due to slice bounds out of range

### ISSUE THREAD

**Issue by jmdacruz** [andreburgaud/crypt2go#7]
There's a potential issue on this line: https://github.com/andreburgaud/crypt2go/blob/cc0f5ac9c509883a6e2ab78755f2963761105711/padding/padding.go#L79
If the input to `Unpad` is an array in which the last byte is a `0`, then this line of code will panic. An error should be returned instead.

**Comment by andreburgaud** [comment]
Thank you @jmdacruz for identifying this issue and proposing a fix. I integrated your changes with a slight twist to separate the 2 errors, but you got it right.
